### ISSUE TITLE
some buttons in discord website trigger browser dragging

### ISSUE THREAD

**Issue by shalva97** [minbrowser/min#1381]
- **Min Version:** 1.17.1
- **Operating system:** Arch

## Expected Behavior
websites shouldnot be able to make browser drag

## Actual Behavior
on Discrod almost all buttons on the right corner trigger dragging and are unclickable

## To Reproduce
go to discord and try to press these buttons:
![image](https://user-images.githubusercontent.com/22417494/102075693-0e04c000-3e20-11eb-93df-2c498f7d5242.png)

updated to 1.17.1

**Comment by Milo123459** [comment]
That is very weird, this sounds like an issue on Discord's end, but I don't know.

**Comment by shalva97** [comment]
It works okay in other browsers so yea...

I also made a video because it is indeed a weird and easily noticeable bug so maybe it is only on Linux? anyways this is what it [looks like](https://www.youtube.com/watch?v=gSpWJ8TzJNE)

**Comment by PalmerAL** [comment]
I think this is probably https://github.com/electron/electron/pull/26496 (or another recent PR that I can't find at the moment); let's try upgrading to the newest version of Electron and see if it still happens.

**Comment by shalva97** [comment]
this is also a problem in Slack when trying to select an emoji...

**Comment by PalmerAL** [comment]
I think 1.17.3 (just released) should fix this; can you try that and see?

**Comment by shalva97** [comment]
nope, still same on 1.17.3

**Comment by PalmerAL** [comment]
Did you update your version of Electron when you upgraded the package? If you go to Min > help > about, Electron should be at least 11.1.0.

**Comment by shalva97** [comment]
there is no Electron in Min > help > about. only chromium and min version. 
![image](https://user-images.githubusercontent.com/22417494/102988039-c6bbb500-452c-11eb-9de0-c586242d83e8.png)

but the Arch package has [#!/usr/bin/electron](https://github.com/archlinux/svntogit-community/blob/e1bbeaf846236b6ef4c2fabb44f666b5345ceec0/trunk/min.js#L1) so Electron version must be v11.1.0 because that what is installed on my system.

**Comment by shalva97** [comment]
I have pulled the master branch and `npm run build` then `electron .` but same problem still

**Comment by PalmerAL** [comment]
There's another Electron PR that was merged today and fixes a really similar issue: https://github.com/electron/electron/pull/27147, so there's a good chance that should fix this as well.

In the meantime, enabling "use separate titlebar" seems to fix it for me (although the mouse cursor in my VM isn't working very well in general, so I'm not totally sure).

**Comment by shalva97** [comment]
I can confirm everything works fine on Electron v11.2.0

you may close this...

**Comment by Milo123459** [comment]
Glad to hear that!
